class IvnentoryPermissions:
    add_product = "add_product"
    change_product = "change_product"
    delete_product = "delete_product"
    view_product = "view_product"
    add_inventorytransaction = "add_inventorytransaction"
    change_inventorytransaction = "change_inventorytransaction"
    delete_inventorytransaction = "delete_inventorytransaction"
    view_inventorytransaction = "view_inventorytransaction"
    add_order = "add_order"
    change_order = "change_order"
    delete_order = "delete_order"
    view_order = "view_order"
    add_supplier = "add_supplier"
    change_supplier = "change_supplier"
    delete_supplier = "delete_supplier"
    view_supplier = "view_supplier"
    view_report = "view_report"
    add_report = "add_report"
    delete_report = "delete_report"
    